name: Build and Test MSX

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build, Unit Testing, and Regression Testing
    environment: testing
    env:
      BuildVersion: 2.0.0
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-10.14]  # Change macos-latest to macos-10.14 for macOS 10.14 (Mojave)
        include:
          - os: windows-latest
            cmake_generator: -G "Visual Studio 17 2022" -A "x64"
            continue-on-error: false
            alias: win64
          - os: ubuntu-latest
            cmake_generator: -G "Unix Makefiles"
            continue-on-error: false
            alias: Linux
          - os: macos-10.14
            cmake_generator: -G "Xcode"
            continue-on-error: false
            alias: Darwin
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.continue-on-error }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Build OpenMP Binaries for MacOS via Homebrew
      if: ${{ matrix.os == 'macos-10.14' }}
      run: |
        brew reinstall --build-from-source --formula ./shell/apple/libomp.rb

    - name: Build
      run: |
        cmake -B build ${{ matrix.cmake_generator }} .
        cmake --build build --config Release --target package

    - name: Run Example on Windows
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        ./build/_CPack_Packages/${{ matrix.alias }}/ZIP/EPANETMSX-${{ env.BuildVersion }}-${{ matrix.alias }}/bin/runepanetmsx ./Examples/example.inp ./Examples/example.msx ./Examples/example.rpt ./Examples/example.out
    
    - name: Run Example on Linux and MacOS
      if: ${{ matrix.os != 'windows-latest' }}
      run: |
        chmod +x ./build/_CPack_Packages/${{ matrix.alias }}/ZIP/EPANETMSX-${{ env.BuildVersion }}-${{ matrix.alias }}/bin/runepanet
        chmod +x ./build/_CPack_Packages/${{ matrix.alias }}/ZIP/EPANETMSX-${{ env.BuildVersion }}-${{ matrix.alias }}/bin/runepanetmsx
        ./build/_CPack_Packages/${{ matrix.alias }}/ZIP/EPANETMSX-${{ env.BuildVersion }}-${{ matrix.alias }}/bin/runepanetmsx ./Examples/example.inp ./Examples/example.msx ./Examples/example.rpt ./Examples/example.out
      
    - name: Upload artifacts
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: build-test-artifacts
        path: |
          build/*.zip
          build/*.tar.gz
